Traceback (most recent call last):
  File "getEngNews.py", line 564, in <module>
    r = run[newsName](whichday)
  File "getEngNews.py", line 166, in __init__
    self.run(seldate)
  File "getEngNews.py", line 180, in run
    driver.get(url) #前往這個網址
  File "S:\TV\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "S:\TV\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "S:\TV\anaconda3\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Reached error page: about:neterror?e=netTimeout&u=https%3A//www.fda.gov/safety/recalls-market-withdrawals-safety-alerts&c=UTF-8&d=%E4%BC%BA%E6%9C%8D%E5%99%A8%20www.fda.gov%20%E8%8A%B1%E4%BA%86%E5%A4%AA%E4%B9%85%E6%99%82%E9%96%93%E9%82%84%E6%98%AF%E7%84%A1%E5%9B%9E%E6%87%89%E3%80%82

