Traceback (most recent call last):
  File "getNews.py", line 791, in _getKeywordNews
    self.driver.get(website) #前往這個網址
  File "S:\TV\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "S:\TV\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "S:\TV\anaconda3\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: Timeout loading page after 300000ms


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "getNews.py", line 974, in <module>
    L = run[newsName](whichday, num=None)
  File "getNews.py", line 777, in __init__
    self._getKeywordNews()
  File "getNews.py", line 794, in _getKeywordNews
    WebDriver.__init__(self)
  File "getNews.py", line 238, in __init__
    self._run()
  File "getNews.py", line 245, in _run
    self.driver = webdriver.Firefox(profile, executable_path='./geckodriver.exe')
  File "S:\TV\anaconda3\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 174, in __init__
    keep_alive=True)
  File "S:\TV\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "S:\TV\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "S:\TV\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "S:\TV\anaconda3\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 無法連線，因為目標電腦拒絕連線。 (os error 10061)

